//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_NET_WEB_FORM_EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Certificado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Certificado()
        {
            this.Tipo_Solicitud = new HashSet<Tipo_Solicitud>();
        }
    
        public int IdCertificado { get; set; }
        public string Nombre { get; set; }
        public string Tipo { get; set; }
        public string Logo { get; set; }
        public string Header { get; set; }
        public string Body { get; set; }
        public string Footer { get; set; }
        public System.DateTime FechaCertificacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tipo_Solicitud> Tipo_Solicitud { get; set; }
    }
}
