//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_NET_WEB_FORM_EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PeriodosVacacionesFuncionario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PeriodosVacacionesFuncionario()
        {
            this.VacacionesTomadasFuncionario = new HashSet<VacacionesTomadasFuncionario>();
        }
    
        public int IdPeriodoVacaciones { get; set; }
        public int FuncionarioId { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaFin { get; set; }
        public int DiasPendientes { get; set; }
        public int UsuarioId { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<int> UsuarioUModificacion { get; set; }
        public Nullable<System.DateTime> FechaUModificacion { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VacacionesTomadasFuncionario> VacacionesTomadasFuncionario { get; set; }
    }
}
