//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_NET_WEB_FORM_EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rol_Operaciones
    {
        public int IdRol_Operaciones { get; set; }
        public int RolId { get; set; }
        public Nullable<int> OperacionId { get; set; }
    
        public virtual Operacion Operacion { get; set; }
        public virtual Rol Rol { get; set; }
    }
}
