//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_NET_WEB_FORM_EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solicitud
    {
        public int IdSolicitud { get; set; }
        public int IdUsuario { get; set; }
        public System.DateTime FechaSolicitud { get; set; }
        public string Estado { get; set; }
        public Nullable<int> TipoSolicitudId { get; set; }
    
        public virtual Tipo_Solicitud Tipo_Solicitud { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
