//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_NET_WEB_FORM_EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VacacionesTomadasFuncionario
    {
        public int IdVacacionesTomadasFuncionario { get; set; }
        public int PeriodoVacacionesId { get; set; }
        public int DiasVacaciones { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaFin { get; set; }
        public string Observaciones { get; set; }
        public int UsuarioCreaId { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<int> UsuarioUModificacion { get; set; }
        public Nullable<System.DateTime> FechaUModificacion { get; set; }
        public string TipoLiquidacion { get; set; }
    
        public virtual PeriodosVacacionesFuncionario PeriodosVacacionesFuncionario { get; set; }
    }
}
